#############################################################################
# Makefile for building: sonig.app/Contents/MacOS/sonig
# Generated by qmake (3.0) (Qt 5.6.1)
# Project:  player.pro
# Template: app
# Command: /Users/francois/Qt/5.6/clang_64/bin/qmake -spec macx-clang CONFIG+=x86_64 -o Makefile player.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_MULTIMEDIAWIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../5.6/clang_64/lib/QtMultimediaWidgets.framework/Headers -I../../5.6/clang_64/lib/QtMultimedia.framework/Headers -I../../5.6/clang_64/lib/QtWidgets.framework/Headers -I../../5.6/clang_64/lib/QtGui.framework/Headers -I../../5.6/clang_64/lib/QtNetwork.framework/Headers -I../../5.6/clang_64/lib/QtXml.framework/Headers -I../../5.6/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../5.6/clang_64/mkspecs/macx-clang -F/Users/francois/Qt/5.6/clang_64/lib
QMAKE         = /Users/francois/Qt/5.6/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = sonig1.0.0
DISTDIR = /Users/francois/Qt/projets/playergit/.tmp/sonig1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/francois/Qt/5.6/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/francois/Qt/5.6/clang_64/lib -framework QtMultimediaWidgets -framework QtMultimedia -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework QtGui -framework QtWidgets -framework QtXml -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		player.cpp \
		playercontrols.cpp \
		playlistmodel.cpp \
		receiveosc.cpp moc_player.cpp \
		moc_playercontrols.cpp \
		moc_playlistmodel.cpp \
		moc_receiveosc.cpp
OBJECTS       = main.o \
		player.o \
		playercontrols.o \
		playlistmodel.o \
		receiveosc.o \
		moc_player.o \
		moc_playercontrols.o \
		moc_playlistmodel.o \
		moc_receiveosc.o
DIST          = ../../5.6/clang_64/mkspecs/features/spec_pre.prf \
		../../5.6/clang_64/mkspecs/qdevice.pri \
		../../5.6/clang_64/mkspecs/features/device_config.prf \
		../../5.6/clang_64/mkspecs/common/unix.conf \
		../../5.6/clang_64/mkspecs/common/mac.conf \
		../../5.6/clang_64/mkspecs/common/macx.conf \
		../../5.6/clang_64/mkspecs/common/sanitize.conf \
		../../5.6/clang_64/mkspecs/common/gcc-base.conf \
		../../5.6/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../5.6/clang_64/mkspecs/common/clang.conf \
		../../5.6/clang_64/mkspecs/common/clang-mac.conf \
		../../5.6/clang_64/mkspecs/qconfig.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../5.6/clang_64/mkspecs/features/qt_functions.prf \
		../../5.6/clang_64/mkspecs/features/qt_config.prf \
		../../5.6/clang_64/mkspecs/macx-clang/qmake.conf \
		../../5.6/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../5.6/clang_64/mkspecs/features/exclusive_builds.prf \
		../../5.6/clang_64/mkspecs/features/default_pre.prf \
		../../5.6/clang_64/mkspecs/features/mac/default_pre.prf \
		../../5.6/clang_64/mkspecs/features/resolve_config.prf \
		../../5.6/clang_64/mkspecs/features/default_post.prf \
		../../5.6/clang_64/mkspecs/features/mac/sdk.prf \
		../../5.6/clang_64/mkspecs/features/mac/default_post.prf \
		../../5.6/clang_64/mkspecs/features/mac/objective_c.prf \
		../../5.6/clang_64/mkspecs/features/warn_on.prf \
		../../5.6/clang_64/mkspecs/features/qt.prf \
		../../5.6/clang_64/mkspecs/features/resources.prf \
		../../5.6/clang_64/mkspecs/features/moc.prf \
		../../5.6/clang_64/mkspecs/features/unix/opengl.prf \
		../../5.6/clang_64/mkspecs/features/uic.prf \
		../../5.6/clang_64/mkspecs/features/unix/thread.prf \
		../../5.6/clang_64/mkspecs/features/file_copies.prf \
		../../5.6/clang_64/mkspecs/features/mac/rez.prf \
		../../5.6/clang_64/mkspecs/features/testcase_targets.prf \
		../../5.6/clang_64/mkspecs/features/exceptions.prf \
		../../5.6/clang_64/mkspecs/features/yacc.prf \
		../../5.6/clang_64/mkspecs/features/lex.prf \
		player.pro player.h \
		playercontrols.h \
		playlistmodel.h \
		receiveosc.h \
		oscpkt.hh main.cpp \
		player.cpp \
		playercontrols.cpp \
		playlistmodel.cpp \
		receiveosc.cpp
QMAKE_TARGET  = sonig
DESTDIR       = 
TARGET        = sonig.app/Contents/MacOS/sonig


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d sonig.app/Contents/MacOS/ || mkdir -p sonig.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: player.pro ../../5.6/clang_64/mkspecs/macx-clang/qmake.conf ../../5.6/clang_64/mkspecs/features/spec_pre.prf \
		../../5.6/clang_64/mkspecs/qdevice.pri \
		../../5.6/clang_64/mkspecs/features/device_config.prf \
		../../5.6/clang_64/mkspecs/common/unix.conf \
		../../5.6/clang_64/mkspecs/common/mac.conf \
		../../5.6/clang_64/mkspecs/common/macx.conf \
		../../5.6/clang_64/mkspecs/common/sanitize.conf \
		../../5.6/clang_64/mkspecs/common/gcc-base.conf \
		../../5.6/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../5.6/clang_64/mkspecs/common/clang.conf \
		../../5.6/clang_64/mkspecs/common/clang-mac.conf \
		../../5.6/clang_64/mkspecs/qconfig.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../5.6/clang_64/mkspecs/features/qt_functions.prf \
		../../5.6/clang_64/mkspecs/features/qt_config.prf \
		../../5.6/clang_64/mkspecs/macx-clang/qmake.conf \
		../../5.6/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../5.6/clang_64/mkspecs/features/exclusive_builds.prf \
		../../5.6/clang_64/mkspecs/features/default_pre.prf \
		../../5.6/clang_64/mkspecs/features/mac/default_pre.prf \
		../../5.6/clang_64/mkspecs/features/resolve_config.prf \
		../../5.6/clang_64/mkspecs/features/default_post.prf \
		../../5.6/clang_64/mkspecs/features/mac/sdk.prf \
		../../5.6/clang_64/mkspecs/features/mac/default_post.prf \
		../../5.6/clang_64/mkspecs/features/mac/objective_c.prf \
		../../5.6/clang_64/mkspecs/features/warn_on.prf \
		../../5.6/clang_64/mkspecs/features/qt.prf \
		../../5.6/clang_64/mkspecs/features/resources.prf \
		../../5.6/clang_64/mkspecs/features/moc.prf \
		../../5.6/clang_64/mkspecs/features/unix/opengl.prf \
		../../5.6/clang_64/mkspecs/features/uic.prf \
		../../5.6/clang_64/mkspecs/features/unix/thread.prf \
		../../5.6/clang_64/mkspecs/features/file_copies.prf \
		../../5.6/clang_64/mkspecs/features/mac/rez.prf \
		../../5.6/clang_64/mkspecs/features/testcase_targets.prf \
		../../5.6/clang_64/mkspecs/features/exceptions.prf \
		../../5.6/clang_64/mkspecs/features/yacc.prf \
		../../5.6/clang_64/mkspecs/features/lex.prf \
		player.pro \
		../../5.6/clang_64/lib/QtMultimediaWidgets.framework/QtMultimediaWidgets.prl \
		../../5.6/clang_64/lib/QtMultimedia.framework/QtMultimedia.prl \
		../../5.6/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../5.6/clang_64/lib/QtGui.framework/QtGui.prl \
		../../5.6/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		../../5.6/clang_64/lib/QtXml.framework/QtXml.prl \
		../../5.6/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile player.pro
../../5.6/clang_64/mkspecs/features/spec_pre.prf:
../../5.6/clang_64/mkspecs/qdevice.pri:
../../5.6/clang_64/mkspecs/features/device_config.prf:
../../5.6/clang_64/mkspecs/common/unix.conf:
../../5.6/clang_64/mkspecs/common/mac.conf:
../../5.6/clang_64/mkspecs/common/macx.conf:
../../5.6/clang_64/mkspecs/common/sanitize.conf:
../../5.6/clang_64/mkspecs/common/gcc-base.conf:
../../5.6/clang_64/mkspecs/common/gcc-base-mac.conf:
../../5.6/clang_64/mkspecs/common/clang.conf:
../../5.6/clang_64/mkspecs/common/clang-mac.conf:
../../5.6/clang_64/mkspecs/qconfig.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_core.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_help.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_location.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_network.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_script.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../5.6/clang_64/mkspecs/features/qt_functions.prf:
../../5.6/clang_64/mkspecs/features/qt_config.prf:
../../5.6/clang_64/mkspecs/macx-clang/qmake.conf:
../../5.6/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../5.6/clang_64/mkspecs/features/exclusive_builds.prf:
../../5.6/clang_64/mkspecs/features/default_pre.prf:
../../5.6/clang_64/mkspecs/features/mac/default_pre.prf:
../../5.6/clang_64/mkspecs/features/resolve_config.prf:
../../5.6/clang_64/mkspecs/features/default_post.prf:
../../5.6/clang_64/mkspecs/features/mac/sdk.prf:
../../5.6/clang_64/mkspecs/features/mac/default_post.prf:
../../5.6/clang_64/mkspecs/features/mac/objective_c.prf:
../../5.6/clang_64/mkspecs/features/warn_on.prf:
../../5.6/clang_64/mkspecs/features/qt.prf:
../../5.6/clang_64/mkspecs/features/resources.prf:
../../5.6/clang_64/mkspecs/features/moc.prf:
../../5.6/clang_64/mkspecs/features/unix/opengl.prf:
../../5.6/clang_64/mkspecs/features/uic.prf:
../../5.6/clang_64/mkspecs/features/unix/thread.prf:
../../5.6/clang_64/mkspecs/features/file_copies.prf:
../../5.6/clang_64/mkspecs/features/mac/rez.prf:
../../5.6/clang_64/mkspecs/features/testcase_targets.prf:
../../5.6/clang_64/mkspecs/features/exceptions.prf:
../../5.6/clang_64/mkspecs/features/yacc.prf:
../../5.6/clang_64/mkspecs/features/lex.prf:
player.pro:
../../5.6/clang_64/lib/QtMultimediaWidgets.framework/QtMultimediaWidgets.prl:
../../5.6/clang_64/lib/QtMultimedia.framework/QtMultimedia.prl:
../../5.6/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../5.6/clang_64/lib/QtGui.framework/QtGui.prl:
../../5.6/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
../../5.6/clang_64/lib/QtXml.framework/QtXml.prl:
../../5.6/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile player.pro

qmake_all: FORCE

sonig.app/Contents/PkgInfo: 
	@test -d sonig.app/Contents || mkdir -p sonig.app/Contents
	@$(DEL_FILE) sonig.app/Contents/PkgInfo
	@echo "APPL????" > sonig.app/Contents/PkgInfo
sonig.app/Contents/Resources/empty.lproj: 
	@test -d sonig.app/Contents/Resources || mkdir -p sonig.app/Contents/Resources
	@touch sonig.app/Contents/Resources/empty.lproj
	
sonig.app/Contents/Info.plist: 
	@test -d sonig.app/Contents || mkdir -p sonig.app/Contents
	@$(DEL_FILE) sonig.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.sonig,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,sonig,g" -e "s,@LIBRARY@,sonig,g" -e "s,@TYPEINFO@,????,g" ../../5.6/clang_64/mkspecs/macx-clang/Info.plist.app >sonig.app/Contents/Info.plist

all: Makefile \
		sonig.app/Contents/PkgInfo \
		sonig.app/Contents/Resources/empty.lproj \
		sonig.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents player.h playercontrols.h playlistmodel.h receiveosc.h oscpkt.hh $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp player.cpp playercontrols.cpp playlistmodel.cpp receiveosc.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r sonig.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_player.cpp moc_playercontrols.cpp moc_playlistmodel.cpp moc_receiveosc.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_player.cpp moc_playercontrols.cpp moc_playlistmodel.cpp moc_receiveosc.cpp
moc_player.cpp: ../../5.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../5.6/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../../5.6/clang_64/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		../../5.6/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlaylist \
		../../5.6/clang_64/lib/QtMultimedia.framework/Headers/qmediaplaylist.h \
		receiveosc.h \
		../../5.6/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../5.6/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		oscpkt.hh \
		../../5.6/clang_64/lib/QtNetwork.framework/Headers/QUdpSocket \
		../../5.6/clang_64/lib/QtNetwork.framework/Headers/qudpsocket.h \
		player.h
	/Users/francois/Qt/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/francois/Qt/5.6/clang_64/mkspecs/macx-clang -I/Users/francois/Qt/projets/playergit -I/Users/francois/Qt/5.6/clang_64/lib/QtMultimediaWidgets.framework/Headers -I/Users/francois/Qt/5.6/clang_64/lib/QtMultimedia.framework/Headers -I/Users/francois/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/francois/Qt/5.6/clang_64/lib/QtGui.framework/Headers -I/Users/francois/Qt/5.6/clang_64/lib/QtNetwork.framework/Headers -I/Users/francois/Qt/5.6/clang_64/lib/QtXml.framework/Headers -I/Users/francois/Qt/5.6/clang_64/lib/QtCore.framework/Headers -F/Users/francois/Qt/5.6/clang_64/lib player.h -o moc_player.cpp

moc_playercontrols.cpp: ../../5.6/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../../5.6/clang_64/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		playercontrols.h
	/Users/francois/Qt/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/francois/Qt/5.6/clang_64/mkspecs/macx-clang -I/Users/francois/Qt/projets/playergit -I/Users/francois/Qt/5.6/clang_64/lib/QtMultimediaWidgets.framework/Headers -I/Users/francois/Qt/5.6/clang_64/lib/QtMultimedia.framework/Headers -I/Users/francois/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/francois/Qt/5.6/clang_64/lib/QtGui.framework/Headers -I/Users/francois/Qt/5.6/clang_64/lib/QtNetwork.framework/Headers -I/Users/francois/Qt/5.6/clang_64/lib/QtXml.framework/Headers -I/Users/francois/Qt/5.6/clang_64/lib/QtCore.framework/Headers -F/Users/francois/Qt/5.6/clang_64/lib playercontrols.h -o moc_playercontrols.cpp

moc_playlistmodel.cpp: ../../5.6/clang_64/lib/QtCore.framework/Headers/QAbstractItemModel \
		../../5.6/clang_64/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		playlistmodel.h
	/Users/francois/Qt/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/francois/Qt/5.6/clang_64/mkspecs/macx-clang -I/Users/francois/Qt/projets/playergit -I/Users/francois/Qt/5.6/clang_64/lib/QtMultimediaWidgets.framework/Headers -I/Users/francois/Qt/5.6/clang_64/lib/QtMultimedia.framework/Headers -I/Users/francois/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/francois/Qt/5.6/clang_64/lib/QtGui.framework/Headers -I/Users/francois/Qt/5.6/clang_64/lib/QtNetwork.framework/Headers -I/Users/francois/Qt/5.6/clang_64/lib/QtXml.framework/Headers -I/Users/francois/Qt/5.6/clang_64/lib/QtCore.framework/Headers -F/Users/francois/Qt/5.6/clang_64/lib playlistmodel.h -o moc_playlistmodel.cpp

moc_receiveosc.cpp: ../../5.6/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../5.6/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		oscpkt.hh \
		../../5.6/clang_64/lib/QtNetwork.framework/Headers/QUdpSocket \
		../../5.6/clang_64/lib/QtNetwork.framework/Headers/qudpsocket.h \
		receiveosc.h
	/Users/francois/Qt/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/francois/Qt/5.6/clang_64/mkspecs/macx-clang -I/Users/francois/Qt/projets/playergit -I/Users/francois/Qt/5.6/clang_64/lib/QtMultimediaWidgets.framework/Headers -I/Users/francois/Qt/5.6/clang_64/lib/QtMultimedia.framework/Headers -I/Users/francois/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/francois/Qt/5.6/clang_64/lib/QtGui.framework/Headers -I/Users/francois/Qt/5.6/clang_64/lib/QtNetwork.framework/Headers -I/Users/francois/Qt/5.6/clang_64/lib/QtXml.framework/Headers -I/Users/francois/Qt/5.6/clang_64/lib/QtCore.framework/Headers -F/Users/francois/Qt/5.6/clang_64/lib receiveosc.h -o moc_receiveosc.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp player.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../5.6/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../../5.6/clang_64/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		../../5.6/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlaylist \
		../../5.6/clang_64/lib/QtMultimedia.framework/Headers/qmediaplaylist.h \
		receiveosc.h \
		../../5.6/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../5.6/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		oscpkt.hh \
		../../5.6/clang_64/lib/QtNetwork.framework/Headers/QUdpSocket \
		../../5.6/clang_64/lib/QtNetwork.framework/Headers/qudpsocket.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

player.o: player.cpp ../../5.6/clang_64/lib/QtMultimedia.framework/Headers/QMediaService \
		../../5.6/clang_64/lib/QtMultimedia.framework/Headers/qmediaservice.h \
		../../5.6/clang_64/lib/QtMultimedia.framework/Headers/QMediaMetaData \
		../../5.6/clang_64/lib/QtMultimedia.framework/Headers/qmediametadata.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/QtWidgets \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qaccessiblewidget.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qerrormessage.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qfilesystemmodel.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qfontdialog.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qprogressdialog.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsanchorlayout.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsgridlayout.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayout.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayoutitem.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicslinearlayout.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsproxywidget.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicstransform.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qgraphicswidget.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qabstractitemdelegate.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qabstractitemview.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qcolumnview.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qdatawidgetmapper.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qdirmodel.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qfileiconprovider.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qheaderview.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qitemdelegate.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qitemeditorfactory.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qlistview.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qlistwidget.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qtableview.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qtreeview.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qtreewidget.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qtreewidgetitemiterator.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qaction.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qformlayout.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qgesture.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qgesturerecognizer.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qlayout.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qlayoutitem.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qshortcut.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qsizepolicy.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qstackedlayout.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qtooltip.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qwhatsthis.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qwidgetaction.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qkeyeventtransition.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qmouseeventtransition.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qcommonstyle.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qdrawutil.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qproxystyle.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qstyle.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qstylefactory.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qstyleoption.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qstylepainter.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qstyleplugin.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qcolormap.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qcompleter.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qscroller.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qscrollerproperties.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qundogroup.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qundostack.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qundoview.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qabstractbutton.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qabstractscrollarea.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qabstractslider.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qabstractspinbox.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qcalendarwidget.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qcommandlinkbutton.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qdatetimeedit.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qdial.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qdialogbuttonbox.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qdockwidget.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qfocusframe.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qfontcombobox.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qgroupbox.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qkeysequenceedit.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qmdiarea.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qmdisubwindow.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qmenu.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qmenubar.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qplaintextedit.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qprogressbar.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qradiobutton.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qrubberband.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qscrollarea.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qscrollbar.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qsizegrip.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qsplashscreen.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qstatusbar.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qtabbar.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qtoolbar.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qtoolbox.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qtoolbutton.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsversion.h \
		../../5.6/clang_64/lib/QtCore.framework/Headers/QSettings \
		../../5.6/clang_64/lib/QtCore.framework/Headers/qsettings.h \
		../../5.6/clang_64/lib/QtNetwork.framework/Headers/QHostAddress \
		../../5.6/clang_64/lib/QtNetwork.framework/Headers/qhostaddress.h \
		../../5.6/clang_64/lib/QtNetwork.framework/Headers/QNetworkInterface \
		../../5.6/clang_64/lib/QtNetwork.framework/Headers/qnetworkinterface.h \
		../../5.6/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../5.6/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		player.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../5.6/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../../5.6/clang_64/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		../../5.6/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlaylist \
		../../5.6/clang_64/lib/QtMultimedia.framework/Headers/qmediaplaylist.h \
		receiveosc.h \
		oscpkt.hh \
		../../5.6/clang_64/lib/QtNetwork.framework/Headers/QUdpSocket \
		../../5.6/clang_64/lib/QtNetwork.framework/Headers/qudpsocket.h \
		playercontrols.h \
		playlistmodel.h \
		../../5.6/clang_64/lib/QtCore.framework/Headers/QAbstractItemModel \
		../../5.6/clang_64/lib/QtCore.framework/Headers/qabstractitemmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o player.cpp

playercontrols.o: playercontrols.cpp playercontrols.h \
		../../5.6/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../../5.6/clang_64/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/QBoxLayout \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/QSlider \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/QStyle \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qstyle.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/QToolButton \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qtoolbutton.h \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/QComboBox \
		../../5.6/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o playercontrols.o playercontrols.cpp

playlistmodel.o: playlistmodel.cpp playlistmodel.h \
		../../5.6/clang_64/lib/QtCore.framework/Headers/QAbstractItemModel \
		../../5.6/clang_64/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		../../5.6/clang_64/lib/QtCore.framework/Headers/QFileInfo \
		../../5.6/clang_64/lib/QtCore.framework/Headers/qfileinfo.h \
		../../5.6/clang_64/lib/QtCore.framework/Headers/QUrl \
		../../5.6/clang_64/lib/QtCore.framework/Headers/qurl.h \
		../../5.6/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlaylist \
		../../5.6/clang_64/lib/QtMultimedia.framework/Headers/qmediaplaylist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o playlistmodel.o playlistmodel.cpp

receiveosc.o: receiveosc.cpp receiveosc.h \
		../../5.6/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../5.6/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		oscpkt.hh \
		../../5.6/clang_64/lib/QtNetwork.framework/Headers/QUdpSocket \
		../../5.6/clang_64/lib/QtNetwork.framework/Headers/qudpsocket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o receiveosc.o receiveosc.cpp

moc_player.o: moc_player.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_player.o moc_player.cpp

moc_playercontrols.o: moc_playercontrols.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_playercontrols.o moc_playercontrols.cpp

moc_playlistmodel.o: moc_playlistmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_playlistmodel.o moc_playlistmodel.cpp

moc_receiveosc.o: moc_receiveosc.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_receiveosc.o moc_receiveosc.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

